const CONFIG = {
  GRAPHQL_URL: process.env.REACT_APP_GRAPHQL_URL,
  GRAPHQL_WS_URL: process.env.REACT_APP_GRAPHQL_WS_URL,
  TOKEN_KEY: process.env.REACT_APP_TOKEN_KEY,
  TRANSACTION_TITLE_MAX_LENGTH: 12,
  TRANSACTION_CREDIT_MIN: 1,
  TRANSACTION_CREDIT_MAX: 99999999,
  DEFAULT_ERROR_MESSAGE: 'Something went wrong.',
  USER_PASSWORD_MIN_LENGTH: 8,
  DEFAULT_TOKEN_EXPIRED: 1000 * 60 * 60 * 24 * 7, // 7 Days,
  CACHE_NAME: {
    IMAGES: 'wager-lite-images',
  },
};

export default CONFIG;
