const CONFIG = {
  GRAPHQL_URL: process.env.REACT_APP_GRAPHQL_URL,
  GRAPHQL_WS_URL: process.env.REACT_APP_GRAPHQL_WS_URL,
  LOCAL_STORAGE_KEY: process.env.REACT_APP_LOCAL_STORAGE_KEY,
  TRANSACTION_TITLE_MAX_LENGTH: 18,
  TRANSACTION_CREDIT_MIN: 0,
  TRANSACTION_CREDIT_MAX: 1000000,
  DEFAULT_ERROR_MESSAGE: 'Something went wrong.',
  USER_PASSWORD_MIN_LENGTH: 8,
  DEFAULT_TOKEN_EXPIRED: 1000 * 60 * 60 * 24 * 7, // 7 Days,
};

export default CONFIG;
